version: '3.3'

services:
  web:
    build: .
    env_file:
      - .env
    command: python /code/manage.py runserver 0.0.0.0:8000 --settings=config.settings.production
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${PROTOTYPE_DB_USER}
      POSTGRES_PASSWORD: ${PROTOTYPE_DB_PASSWORD}
      POSTGRES_DB: ${PROTOTYPE_DB_NAME}
    volumes:
      - prototype-db:/var/lib/postgresql/data/

volumes:
  prototype-db: