version: '3.3'

services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - static_data:/vol/web
    depends_on:
      - db

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${PROTOTYPE_DB_USER}
      POSTGRES_PASSWORD: ${PROTOTYPE_DB_PASSWORD}
      POSTGRES_DB: ${PROTOTYPE_DB_NAME}
    volumes:
      - prototype-db:/var/lib/postgresql/data/

volumes:
  prototype-db:
  static_data: